redox-os/orbtk

src/button.rs
src/label.rs
src/progress_bar.rs
src/rect.rs
src/sdl2/mod.rs
src/widget.rs

* Use `Point` for the positioning in `Rect`
* Wrap `Point` with `Option` for defaulting to `None`
* Remove `Rect` arguments in widget constructors
* Use `Rect::default()` for filling in `rect` fields instead
* Add `Widget::position()` builder method for all widgets
* Add `Rect::get_point()` to make it less repetitive to get a `Point` within `Option`
* Apply necessary fixes for `Point` related warnings
Btw, there are still errors about using the `Widget` trait as an object and stuff about iterators.

Use `Point` for `Rect` and tons of refactoring.

---

src/enter.rs
src/lib.rs
src/text_box.rs

By using the `on_enter()` builder for `TextBox`, it automatically uses the custom callback instead of the default multi-line functionality without the need to return `false`.

Cleanup `Enter` for `TextBox`

---

src/lib.rs
src/menu.rs
src/renderer.rs
src/window.rs

**Problem:** User interface is missing menus.
**Solution:** Add menu support in orbtk.
**Changes introduced by this pull request:**
- menu.rs contains the majority of the changes. I attempted to extrapolate from existing work and create a functional and intuitive foundation for menus.
- lib.rs (the example program) contains a working example of a menu.
- lines in renderer.rs and window.rs are for the separator.
**Drawbacks:** Currently, the menu must be added to the window last so that it is drawn on top of the other elements.
**TODOs:** In order to address the above drawback, I believe the next step would be implementing a dedicated menu bar which is always rendered last and can have menus added to it (rather than directly placed on the window).
**State:** Ready. However, I would …

Add basic menu functionality. Working example in src/lib.rs

---

examples/filtered.rs
src/callback.rs
src/text_box.rs

This PR adds:
* An EventFilter trait. It implements two methods, one to call the filter, other to set it. 
The filter is just a closure that takes in the Event, and either returns None if the filter caught it and handled it in a special way, or the Event it received if it doesn't do anything special and wants the default handler to deal with it.
* An implementation of EventFilter on TextBox

Add input event filtering for textboxes.

---

examples/list.rs
src/widgets/list.rs
src/widgets/mod.rs

A `List` stores `Entry` objects. Each `Entry` can store `Widget`s inside. The `List` renders Entries in the order they were pushed onto it.

Add a List widget

---

examples/canvas.rs
examples/filtered.rs
examples/list.rs
examples/widgets.rs
src/event.rs
src/widgets/list.rs
src/window.rs

- there is now a concept of a `selected` entry, which will be highlighted
- up/down changes the current selection rather than scrolling (but will scroll if entry is outside the viewable area)
- responds to `ScrollEvent`
- supports `home`/`end` to jump to top and bottom
- `enter` simulates a click on the entry
This PR breaks `exec` up into a few pieces that can be called independently. This allows FileManager to still maintain its own event queue. In the future I'd like to put everything back behind `exec`, but not at the window level.
Instead I think it would be nice to have an `Application` which is capable of housing multiple `Window`s and accepts some sort of callback that allows the application to hook into the application loop. Which would allow behavior like in this FileManager PR …

support for FileManager in List and Window

---

src/widgets/list.rs

I've noticed, that scroll in orbtk List widget is inverted, which affects Redox file manager.
Comparing to orbutils browser, which doesn't use orbtk, `scroll_event` value is subtracted from current offset:
https://github.com/redox-os/orbutils/blob/master/src/browser/main.rs#L707
```Rust
offset.1 = cmp::max(0, cmp::min(cmp::max(0, max_offset.1 - window_h), offset.1 - scroll_event.y * 48));
```
But in orbtk `List` value is added instead, so changing sign should fix direction.

Fix scroll direction in List widget

---

src/widgets/list.rs

Recent changes broke using up/down arrows to select. This fixes it by returning `scroll` to it's previous state, and implementing the changes (scroll direction and speed) elsewhere.

fix List scrolling

---

src/widgets/button.rs

If you click and hold on a button and move the cursor to another button while still holding down, both buttons become highlighted. This causes the `pressed` state to be reset if the mouse exits the button, regardless of if the left button is pressed

Unpress buttons regardless of left_button state

---

examples/exampletheme.css
examples/themed.rs
src/traits/mod.rs
src/traits/style.rs
src/widgets/label.rs
src/widgets/menu.rs

Here is my idea of a trait to allow apps to add classes/pseudoclasses to their widgets for use as conditional styling. For example, on the orbutils calendar the current date could be given a "today" class, so the background colour for that label can live entirely within the CSS file for the application.
**TODO**:
- Add `Style` trait to other relevant classes, and make sure they use the correct Selector object and don't create their own in `draw`
- Add "without_class" and similar so apps can remove classes that were added
**Downsides**: Apps that want to change a single widget's style needs to create a theme CSS that includes all the defaults. This could be mitigated if we could merge two theme objects, so you can create a default theme and then add extras from another.

[WIP] Allow apps to add classes and pseudoclasses to widgets

---

examples/themed.rs
src/theme.rs
src/traits/style.rs
src/widgets/button.rs
src/widgets/combo_box.rs
src/widgets/label.rs
src/widgets/list.rs
src/widgets/menu.rs
src/widgets/progress_bar.rs
src/widgets/text_box.rs

Move implementation of Style's with/without_class/pseudoclass into the trait, to reduce repeated code.
There are quite a few sub-selectors inside widgets, like combo-box-toggle or menu-button. The classes that are added to a widget don't affect those selectors yet. Once complex selectors are implemented we could set them as children of the main selector, so to style them you do `combo-box.class > combo-box-toggle`. Better yet, if we implement pseudoelements they could be styled like `combo-box.class::toggle`. I added TODO comments to all these places

Add Style trait to remaining widgets, allow apps to remove classes

---

src/window.rs

was causing unantialiased fonts. thinking that Window::new should be deprecated in favour of WindowBuilder

Initialize font correctly in WindowBuilder

---

src/widgets/combo_box.rs

From chat:
@flovanro Hi!  I'm trying to use ComboBox : if I place the widget using  .position(x,y)  when x is > 200 the entries are progressively chopped until they completely disappear.
I think there is something wrong when checking if the entry fits inside the flyout rect (or the Entry rect.width is not updated correctly). 
(orbtk/src/widgets/combo_box.rs  line 87)
let mut point = Point::new(rect.x + offset.x, rect.y + rect.height as i32 / 2 - 8);
for c in self.text.get().chars() {
if point.x + 8 <= rect.width as i32 - 2 * offset.x {                                            <--------- commenting out this line  I get the text back, but it is not a proper fix. 
renderer.char(point.x, point.y, c, theme.color("color", &selector));
}
point.x += 8;
}
Are you affected by the same bug? Could …

Fix bug when x > 200 the entries of Combobox are not drawn.

---

README.md

The current link does not point to a current wikipedia article.
I updated the readme with the current link for the `Entity Component System Pattern`.

updated readme - fixed ECS link

---

examples/calculator.rs

Here is screenshot of result of 22/7
before 
after

Fix up calcurator example: show only 9 digits to fit in the display

---

crates/utils/src/string16.rs

Fix for #120.
Looking at the other methods, other changes will probably be required to actually correctly support non-BMP chars, but I focused on the one I reported for my first PR here.

Support non-BMP in String16::push

---

crates/shell/src/minifb/mod.rs

minifb needs `title = false` to achieve a true borderless window on macos.
This PR sets `title = false` if `borderless == true`
We could also expose the title flag or just check if the title is an empty string and then set `title = !borderless && title.len() == 0`

Fix borderless on mac

---

crates/api/src/layout/stack.rs

Currently the StackLayout uses the height/width in cross-dimension from the last child.
This PR changes that to use the max height/width in cross-dimension
Fixes #168

Fix stack layout to use the max height/width

---

crates/api/src/event/key.rs
crates/api/src/event/mod.rs
crates/api/src/event/mouse.rs
crates/api/src/layout/grid.rs
crates/api/src/layout/mod.rs
crates/api/src/properties/layout/constraint.rs
crates/api/src/properties/layout/row.rs
crates/api/src/properties/mod.rs
crates/api/src/services/settings.rs
crates/api/src/systems/layout_system.rs
crates/api/src/systems/mod.rs
crates/api/src/widget/build_context.rs
crates/api/src/widget/context.rs
crates/api/src/widget/mod.rs

I fixed two typos in doc comments during reading the source code.
Then i checked the crates::api, more to come

Fixed typos in doc comments

---

crates/css-engine/src/lib.rs
crates/css-engine/src/theme.rs
crates/render/src/concurrent/mod.rs
crates/render/src/raqote/mod.rs
crates/render/src/web/image.rs
crates/render/src/web/mod.rs
crates/shell/src/window.rs
crates/tree/src/lib.rs
crates/utils/src/alignment.rs
crates/utils/src/color.rs
crates/utils/src/rectangle.rs
crates/utils/src/string16.rs
crates/widgets/src/canvas.rs
crates/widgets/src/grid.rs
crates/widgets/src/list_view.rs
crates/widgets/src/popup.rs
crates/widgets/src/slider.rs
crates/widgets/src/text_block.rs
crates/widgets/src/text_box.rs
crates/widgets/src/toggle_button.rs
crates/widgets/src/window.rs

Fixed typos in docs comments in all crates.
Broke some comments that wider than 120 chars into multiple lines.
Rewrote some docs.

Docs typos fix

---

crates/api/src/render_object/rectangle.rs

Currently the border-radius of one corner can overlap with another corner.
ATM in this cases `render_circle `might be called which results in circles larger than the width and height

Add a basic overlap avoidance algorithm to border-radius

---

crates/utils/src/point.rs

Not sure if this is something we want on these types. I needed it in my project and it didn't feel right to make an `fn point_distance(point_a: Point, point_b: Point) -> f64` just for my project.

Adds fn to get distance between two points

---

crates/widgets/src/combo_box.rs

I was annoyed that `ComboBox`es stay open when you click on an item. This pull request changes that.

Close `ComboBox` when an item is selected

---

crates/widgets/src/combo_box.rs

After the last pull request ([combo-box-close](https://github.com/redox-os/orbtk/pull/200)) this code was dead, but forgot to delete it 👼

ComboBox: Removed dead code

---

crates/widgets/src/progress_bar.rs

When the rendering was slow, you could see the progressbar is empty before the first update() is called. This is not a problem anymore, just in case calling update() from init since the code that would set the init value would be the same as update().
Indicator vertical-align set to center.This fixes the drawing position of the indicator when the progress bar is a child of a Stack.

Pgbar improvements

---

README.md

The `.child` should just use 1 argument. But the example use 2 arguments.

fixed the code can't run

---

crates/api/src/widget/widget_container.rs

I have added a get_name() fn to reduce the duplicate code, replaced TypeId::of calls with std::any::type_name.
Adjusted the panic messages.
In the get_mut() fn i cannot modify the code, because self is already borrowed as mutable.

Improve #237

---

crates/api/src/widget/widget_container.rs
examples/widgets.rs

when adding a new item to the ComboBox, the app will panic.
use method clone_or_default(), that takes care to get that right.
* A typo correction
* Showing an 'Add' button only make sense, if the item length is less then our intended max (here: we only allow 5 items)
* Showing a 'Remove' button only make sense, if the item length is bigger then 1 (an item exists in the list)
Updated the code to respect this constraints.

Bugfix: example -> widgets

---

crates/utils/src/string16.rs

Hi,
i have noticed that the toolkit is able to store and load setting configuration using ron format and serde. For an application that i'm made i need to save String16 type, but the type does not implement the needed Serialize Deserialize traits. I made this change locally, but I think that this could be generally useful and should not generate any problems, so i pushed this change.
Thanks for the attention

Adding Serialize Deserialize derive for String16

---

crates/api/src/layout/padding.rs

Hi,
i have found a bug that does not allow to the PaddinLayout to resize on window size change. 
From what i have understood, the layout calculation is based on 2 functions: measure and arrange (both provided by Layout trait).
First measure is called (it is supposed to calculate the size, keeping into consideration all it's children). When completed, it return a DirtySize object. If this object is "dirty", the layout function is called (it is supposed to calculate the position of the object and all it's children), otherwise not.
The problem is that when the window resize, only the layout function is aware of this change (because the new size is passed as parameter) and, if the measure function return a "clean" DirtySize, the layout function is never called, making impossible to resize the …

Padding Layout does not resize fix

---

crates/theme/assets/dark/dark.ron
crates/theme/assets/light/light.ron
crates/widgets/src/toggle_button.rs

Hi,
i have noticed that the ToggleButton widget do not change background color on toggle. After verify that the button effectively work and that it is only a visual bug, i found that on theme files the "toggle-button" theme (used on ToggleButton widget) is missing on both light and dark theme. I have simply copied the button theme and renamed it to "toggle-button" since, as i remember, the ToggleButton widget had the same theme as the Button widget (this should be a regression because i remember that it worked a week ago).
Thanks for the attention,
Have a nice day

ToggleButton animation

---

crates/widgets/src/tab_widget.rs

Hi,
i have noticed a little problem on the TabWidget: if the close button visibility is setted from the outside of the widget, the change is ignored and setted true anyway. Using an example like:
```
TabWidget::new()
.close_button(false)
.tab("Tab header 1",TextBlock::new().text("Tab content 1").build(ctx))
.tab("Tab header 2",TextBlock::new().text("Tab content 2").build(ctx))
.tab("Tab header 3",TextBlock::new().text("Tab content 3").build(ctx))
.build(ctx);
```
can be noticed that the close button will appear anyway.
The problem is inside the TabWidget template function:
```
impl Template for TabWidget {
fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
self.name("TabWidget")
.style("tab_widget")
.close_button(true)           //HERE
.child(
Grid::new() …
```

TabWidget close button visibility cannot be toggled during template construction

---

crates/render/src/common.rs
crates/render/src/raqote/mod.rs
crates/render/src/web/mod.rs
crates/utils/src/rectangle.rs

This enables the possibility of doing multiple calls to `clip` in raqote and restore its previous state before, in that scenery OrbTk should fail to track the path dimensions and `restore` would fail to reverse the clip operation.

Multi-level clip

---

README.md

Is it a typo?
`cargo fmt` add the end -> `cargo fmt` at the end
@FloVanGH

Is it a typo?

---

CHANGELOG.md
Cargo.lock
crates/api/src/widget_base/widget_container.rs

* use custom property names in ron theme files for `Brush`, `String`, `f32`, `f64` and `Thickness`

use custom property names in theme

---

CHANGELOG.md
crates/widgets/src/behaviors/text_behavior.rs
crates/widgets/src/numeric_box.rs
crates/widgets/src/password_box.rs
crates/widgets/src/text_box.rs

I think changing `lost_focus_on_activation` to `lose_focus_on_activation` better conveys the intended meaning since `lost` implies, at least in my understanding, that something already happend. `lose` indicates it will happen on activation. Maybe a native speaker could weigh in on this.

Change tense of `lost_focus_on_activation` to better convey meaning.

---

CHANGELOG.md
crates/api/src/layout/grid.rs

This should fix #170.
As this should only change the grid layout behavior for grid in grid layouts, this shouldn't have any effect on other parts.

Fix grid auto

---

Cargo.lock
crates/api/Cargo.toml
crates/api/src/layout/fixed_size.rs
crates/api/src/properties/mod.rs

There was a bug in the layout at the moment of calc the width of a `TextBlock` if it was multiline, this fixes that and also implements `IntoPropertySource` for `PathBuf` so now is possible use it as a widget property.

Fix multiline text and implement IntoPropertySource for PathBuf

---

crates/api/Cargo.toml
crates/api/README.md

Update the references to the dirs-next crate.

dirs-next: reference update

---

crates/api/src/widget_base/context.rs

Commit a338c852cb5acf62081089f1adbfa0d0c80a3698 made private the entity member of the Context struct and introduced the entity() getter method().
It broke my app, because it is used to change into another widget's context to do stuff.
This PR fixes this.
@FloVanGH

Add change_into() method

---

crates/api/src/widget_base/context.rs

Improve the inline documentation text to describe the usage of the context structure.

widget/context: Improve documentation text

---

crates/widgets/src/popup.rs

If you need to handle Key events inside a popup widget, we can enable the KeyDownHandler as a default behaviour of the widget.

widgets/popup: add the KeyDownHandler

---

README.md

Found 2 dead links among the subcrates in readme.md.
@mentions of the person or team responsible for reviewing proposed changes.

Fix typos in links to subcrates in Readme.md

---

crates/utils/build.rs

See rust-lang/cargo#8925
I confirmed this fixes the build issue by pointing to my branch:
orbtk = { git = "https://github.com/xixixao/orbtk.git", branch = "xixixao-patch-1" }

Fix utils build script

---

Cargo.lock
README.md

widgets' example has been removed on 25798a7
```
$ cargo run --example widgets --features miniraq --no-default-features
error: no example target named `widgets`
```

fix README.md, widgets' example has been removed on 25798a7
