src/event.rs
src/lib.rs

Have the computer do the work for you, not do the work for it.

Use existing values to keep tract of x and y in example

---

src/button.rs
src/label.rs
src/lib.rs
src/place.rs
src/point.rs
src/progress_bar.rs
src/rect.rs
src/sdl2/mod.rs
src/text_box.rs

Partly fixes [redox-os/redox issue #388](https://github.com/redox-os/redox/issues/388)

Change isize/usize args & fields to i32/u32

---

src/button.rs
src/color.rs
src/label.rs
src/lib.rs
src/progress_bar.rs
src/text_box.rs
src/widget.rs

Each widget shares common fields, therefore I created a `WidgetCore` type so that each widget is API consistent.
TODO: Finish up menu.rs

API simplification

---

examples/canvas.rs
src/canvas.rs
src/lib.rs
src/renderer.rs
src/window.rs

I don't know how good/bad I made this, but I feel like it's gonna work alright. I want you to rate it before I implement more fancy drawing functions(line, rect, text, image)
Here's a (bad) demo of it: https://gfycat.com/BruisedSmoggyFritillarybutterfly
edit: I don't understand why the CI failed, it works on my machine ¯\\\_(ツ)_/¯

Canvas widget.

---

examples/canvas.rs
src/canvas.rs

Sorry for breaking this the first time.

Fix the canvas example

---

examples/widgets.rs
src/button.rs
src/label.rs
src/menu.rs
src/progress_bar.rs
src/renderer.rs
src/window.rs

Add borders to buttons, adjust color scheme and menu style

Button borders

---

src/renderer.rs
src/theme.rs
src/widgets/button.rs
src/window.rs

Slightly less ugly buttons!
Doesn't build unless I point to my copies of orbclient, orbimage, and orbfont. I'm pretty sure this is just because crates.io needs to be updated.

Add linear gradient to renderer, and linear gradient to buttons

---

src/widgets/button.rs

Fix the noob mistake

---

examples/grid.rs
src/widgets/grid.rs

Added clear() to Grid and example

---

examples/exampletheme.css
examples/themed.rs
src/lib.rs
src/theme.rs
src/window.rs

Some changes necessary to allow the user to specify a theme. Most of it is simple, obvious stuff that would have eventually been put in (like `from_file` constructors). Also added a `WindowBuilder` to allow the user to optionally specify theme etc.

Allow the user to specify a theme

---

examples/filtered.rs
examples/widgets.rs
src/event.rs
src/lib.rs
src/widgets/combo_box.rs
src/widgets/list.rs
src/widgets/text_box.rs
src/window.rs

Replaced the single key events (UpArrow, DownArrow, Enter, Text, ...) by KeyPressed and KeyReleased. This should provide more flexibility. Also updated the events in all relevant structs.

Implement KeyPressed and KeyReleased events.

---

examples/filtered.rs

The second textbox now filters properly letters and allows numbers.

Fixes issue #84

---

README.md

Adds some documentation so others don't run into the issue I did.
Resolves #87

Document required version of Rust

---

examples/themed.rs
examples/widget_tree.rs
examples/widgets.rs

Just fixed three examples for working with renaming of arrange_children

arrange -> arrange_children

---

crates/utils/src/point.rs

Ability to add and subtract `Point`s like this: `point_a + point_b`.

impl `Add` & `Sub` for `Point`

---

crates/api/src/systems/render_system.rs
crates/shell/src/minifb/window.rs
crates/shell/src/native/mod.rs

fixing warnings

---

examples/popup.rs

This PR adds the missing widget examples.

[WIP] Missing examples

---

crates/widgets/src/numeric_box.rs
examples/numeric_box.rs

Fixes #246.
Added ActivateHandler and ChangedHandler suggested by @rzerres.
Values clamped to boundaries suggested by @michalsieron.

Numbox improve (fix #246)

---

crates/render/src/web/mod.rs
crates/shell/src/web/mod.rs
crates/shell/src/web/window.rs
crates/shell/src/web/window_builder.rs

Fix for my previous PR. Should build for web now

FIX: Switch to point struct

---

crates/api/src/macros.rs
crates/api/src/widget/state.rs
crates/api/src/widget/template.rs

I added some documentation to the basic stuff (widget macro, Template, and State traits).
I hope it's technically correct, please check @FloVanGH.
@tzargoth please check the grammar and spelling.
Thank you.

Basic docs

---

Cargo.lock
crates/api/Cargo.toml
crates/api/src/layout/fixed_size.rs
crates/api/src/render_object/text.rs

The goal of this PR is give to `TextBlock` the capability of display multiline strings(before it ignores the end of line and put whitespace)

multiline support for TextBlock

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Node.toml
crates/api/Cargo.toml
crates/render/Cargo.toml
crates/render/src/common.rs
crates/render/src/lib.rs
crates/render/src/raqote/mod.rs
crates/shell/Cargo.toml
crates/shell/src/lib.rs
crates/shell/src/orbclient/mod.rs
crates/shell/src/orbclient/window.rs
crates/shell/src/orbclient/window_builder.rs
crates/theme/assets/dark/dark.ron
crates/widgets/Cargo.toml
crates/widgets/src/behaviors/text_behavior.rs
crates/widgets/src/tab_widget.rs
examples/widgets.rs

*  fix memory leak on OrbClient #314 
*  Performance improvements OrbClient and raqote #315 #306 
*  Select all characters on text input by double click
*  Fix styling issues in `TabWidget` #320
@mentions of the person or team responsible for reviewing proposed changes.

Memory fix

---

examples/README.md

fixes the image positions in the examples README

trying to fix img pos

---

crates/widgets/src/behaviors/text_behavior.rs

Fix one off error in `del` text behavior

---

examples/widgets.rs

Make displayed selection correspond to selected item number in widgets example

---

README.md

Fix broken link to OrbTk template :)

Fix broken link to OrbTk template

---

crates/render/src/concurrent/mod.rs
crates/render/src/raqote/font.rs
crates/render/src/raqote/mod.rs
crates/render/src/web/mod.rs
examples/canvas.rs

Make set_transform work with fill_text in raqote

---

CHANGELOG.md
Cargo.lock
crates/api/src/application/window_adapter.rs
crates/api/src/event/mod.rs
crates/api/src/event/text_input.rs
crates/api/src/widget_base/context.rs
crates/shell/Cargo.toml
crates/shell/src/minifb/window.rs
crates/shell/src/minifb/window_builder.rs
crates/shell/src/orbclient/window.rs
crates/shell/src/web/window.rs
crates/shell/src/window_adapter.rs
crates/widgets/src/behaviors/text_behavior.rs
crates/widgets/src/master_detail.rs
crates/widgets/src/password_box.rs
crates/widgets/src/text_box.rs
examples/showcase.rs

* Implement `TextInput` event for robuster text input handling
* Should fix wrong text input on Windows

Text input

---

CHANGELOG.md
crates/api/src/application/window_adapter.rs
crates/api/src/event/mouse.rs
crates/api/src/macros.rs
crates/api/src/properties/widget/focus_state.rs
crates/api/src/systems/event_state_system.rs
crates/api/src/widget_base/mod.rs
crates/api/src/widget_base/widget_container.rs
crates/theme/assets/common/colors.ron
crates/theme/assets/dark/dark.ron
crates/theme/assets/light/light.ron
crates/theming/src/config/theme_config.rs
crates/theming/src/selector.rs
crates/theming/src/theme.rs
crates/widgets/src/behaviors/text_behavior.rs
crates/widgets/src/button.rs
crates/widgets/src/combo_box.rs
crates/widgets/src/list_view.rs
crates/widgets/src/switch.rs
examples/showcase.rs

* Add `EnterEvent` and `LeaveEvent`
* Add `hover` property and selector state to all widgets
* Add `on_enter` and `on_leave` callback to `MouseHandler`

Mouse hover

---

CHANGELOG.md
crates/utils/src/brush.rs

Update the documentation part of gradient implementation for brush.rs
@FloVanGH

brush: update documentation section

---

crates/utils/src/brush.rs

Improve given text with missing prose for 
* document directions
* document displacement points

Update brush documentation

---

crates/widgets/src/master_detail.rs

Improve documentation text on widget `master_detail`

widgets/master_detail: improve documentation text
